# -*- coding: utf-8 -*-
"""Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZrBam47N-EpU42vvuK9RbgTXesJP3GgP

Amsterdam is a city with a large variety of flowers with several florists connected by bidirectional roads, each of which has a travel time. Each of the floristry may sell one or more kinds of flowers. Frank and Gorgi are brothers, and their mother is under a spell that will be broken by a bouquet of **k** different flower that **k** is the number of all types of flowers which are available in florists Amsterdam.

At first, Frank and Gorgi are at floristry 1 (each of the florists is numbered consecutively from 1 to **n**), and according to the situation, they should collect all types of flowers, and in order to save time, they will divide the list of flowers between them. Determine the total travel time for the boys to purchase all types of flowers, finally meeting at floristry **n**. Their paths may intersect, they may backtrack through floristry **n**, and one may arrive at a different time than the other. The minimum time to determine is when both have arrived at the destination.

For example,  there are **n = 5** florists selling **k = 3** types of flowers. The following graph shows a possible layout of the florists connected by **m = 5** paths. Each of nodes is labeled **floristry number / flower types offered / boy(s) that visit(s)**. Here **F** and **G** represent Frank and Gorgi, respectively. In this example, both of boys take the same path, i.e. **1 &#8594; 3 &#8594; 5** and arrive at time **15 + 5 = 20** having purchased all three types of flowers. Neither of them visits floristry **2** or **4**. <br/>
<img src="Images/Blank_diagram.png" width="400"/>

## Input Format

The first line contains 3 space-seperated integers: <br/>
**n**(the number of floristries in Amsterdam), **m**(the number of roads), and **k**(the number of flower types sold in Amsterdam), respectively.<br/>
Each line **i** of the **n** subsequent lines ($1 \leq i \leq n$) describes a floristry as a line of space separated integers. Each line takes the following form: <br/>
   * The first integer, $t_i$, denotes the number of flower types that are sold at floristry **i**.
   * Each of the $t_i$ subsequent integers on the line describes a type of flower sold at floristry **i**, denoted by $S_{ij}$, where $1 \leq j \leq t_i$

Each line **z** of the **m** subsequent lines ($1 \leq j \leq m$) contains 3 space-separated integers that describe a road. The first two integers, $u_z$ and $v_z$, describe the two florists it connects. The third integer, $w_z$, denotes the amount of time it takes to travel the road.

## Constraints

* $ 2 \leq n \leq 10^3 $
* $ 1 \leq m \leq 2 \times 10^3 $
* $ 1 \leq k \leq 10 $
* $ 0 \leq t_i \leq k $
* $ 1 \leq S_{ij} \leq k $
* All $S_{ij}$ are different for every fixed *i*
* $ 1 \leq u_z , v_z \leq n $
* $ 1 \leq w_z \leq 10^4 $
* Each road connects 2 distinct florists.
* Each pair of florists is directly connected by no more than 1 road.
* It's possible to get to any floristry from any other florist.
* Each type of flower is always sold by at least one florist.

## Output Format

Print the minimum amount of time it'll take for the boys to collectively purchase all **k** types of flowers and meet up at florist **n**.

## Sample Input

5 5 5 <br/>
1 1 <br/>
1 2 <br/>
1 3 <br/>
1 4 <br/>
1 5 <br/>
1 2 10 <br/>
1 3 10 <br/>
2 4 10 <br/>
3 5 10 <br/>
4 5 10

## Sample Output

30

## Explanation

<img src="Images/diagram2.png" width="400"/>
<br/>
Frank can travel $1 \rightarrow 2 \rightarrow 4 \rightarrow 5$ and buy flower at all of the florists on his way. <br/>
Gorgi can travel $1 \rightarrow 3 \rightarrow 5$, and buy flower from the third florists only.

Now, You should implement the function **solve**.
<br/> At last, Pay Attention that you have a **time limit of 9s** for each test that if your code exceeds that limit for any of these tests, you'll get **FAIL** for that test.
"""

def solve(N, M, K, NUMS, roads): 
    queue = []
    delay_queue = []
    recieved_flower = []
    Adjacent_M = np.ones((N,N))*np.inf
    for i in range(M):
        road = roads[i]
        Adjacent_M[int(road[0])-1,int(road[1])-1] = road[2]
        Adjacent_M[int(road[1])-1,int(road[0])-1] = road[2]
    if NUMS[0][0]==0:
        First_item = [0,set(),0]
    elif NUMS[0][0]==1:
        First_item = [0,set([NUMS[0][1]]),0]
    else:
        First_item = [0,set(NUMS[0][1:]),0]
    queue.append(First_item)
    delay_queue.append(0)
    while (len(queue)!=0):
        r = np.array(delay_queue).argmin()
        req = queue.pop(r)
        d = delay_queue.pop(r)
        node = req[0]
        flower_set = req[1]
        delay = req[2]
        if node != N-1:
            roads = Adjacent_M[node].copy()
            num_roads = sum(roads!=np.inf)
            for i in range(num_roads):
                index = roads.argmin()
                new_node = index
                new_flower_set = flower_set
                if NUMS[index][0]==1:
                    new_flower_set = set.union(flower_set, set([NUMS[index][1]]))
                elif NUMS[index][0]!=0:
                    new_flower_set = set.union(flower_set, set(NUMS[index][1:]))
                new_delay = delay + Adjacent_M[node,new_node]
                new_req = [new_node,new_flower_set,new_delay,node]
                if len(queue)==0:
                    queue.append(new_req)
                    delay_queue.append(new_delay)
                elif new_req not in queue:
                    queue.append(new_req)
                    delay_queue.append(new_delay)
                roads[index]=np.inf
        else:
            recieved_flower.append(flower_set)
            if len(flower_set) == K:
                return delay
            list_len = len(recieved_flower)
            for i in range(list_len-1):
                new_set = set.union(recieved_flower[-1], recieved_flower[i])
                if len(new_set) == K:
                    return delay

"""## Grading

By Running the below cell, you'd test your code with 10 test cases we gave to you, But be aware that there are more tests that will determine your grade in addition to these ten tests.
"""

import time
import numpy as np
pass_count = 0
test_count = 10
Time_Limit = 9
recieved_req = []
#for i in range(test_count):
for i in range(test_count):
    print("Test", (i + 1))
    file_in_name = "In" + str(i + 1)
    file_out_name = "Out" + str(i + 1)
    f = open("Inputs/" + file_in_name + ".txt", 'r')
    N, M, K = map(int, f.readline().split())
    NUMS = []
    roads = []
    for i in range(N):
        nums = list(map(int, f.readline().split()))
        NUMS.append(nums)
    for i in range(M):
        road = list(map(int, f.readline().split()))
        roads.append(road)
    start_time = time.time()
    result = solve(N, M, K, NUMS, roads)
    end_time = time.time()
    f_out = open("Outputs/" + file_out_name + ".txt", 'r')
    true_output = int(f_out.read())
    if result == true_output and Time_Limit >= end_time - start_time:
        print("PASS.", "Your answer which is True: ", result, ". Time consumed: ", end_time - start_time, "s")
        pass_count += 1
    else:
        print("FAIL!", "your minimum time: ", result, "True answer: ", true_output, ". Time consumed: ", end_time - start_time, "s")
        
print("Percentage of success: ", (pass_count / test_count) * 100)